cmake_minimum_required(VERSION 3.16)
project(jsk_recognition_msgs)

find_package(ament_cmake REQUIRED)
find_package(rosidl_default_generators REQUIRED)
find_package(std_msgs REQUIRED)
find_package(geometry_msgs REQUIRED)
find_package(sensor_msgs REQUIRED)
find_package(pcl_msgs REQUIRED)
find_package(builtin_interfaces REQUIRED)
find_package(action_msgs REQUIRED)
find_package(jsk_footstep_msgs REQUIRED)

rosidl_generate_interfaces(${PROJECT_NAME}
  "msg/Accuracy.msg"
  "msg/BoolStamped.msg"
  "msg/BoundingBox.msg"
  "msg/BoundingBoxArray.msg"
  "msg/BoundingBoxArrayWithCameraInfo.msg"
  "msg/BoundingBoxMovement.msg"
  "msg/Circle2D.msg"
  "msg/Circle2DArray.msg"
  "msg/ClassificationResult.msg"
  "msg/ClipResult.msg"
  "msg/ClusterPointIndices.msg"
  "msg/ColorHistogram.msg"
  "msg/ColorHistogramArray.msg"
  "msg/ContactSensor.msg"
  "msg/ContactSensorArray.msg"
  "msg/DepthCalibrationParameter.msg"
  "msg/DepthErrorResult.msg"
  "msg/ExifGPSInfo.msg"
  "msg/ExifTags.msg"
  "msg/HandPose.msg"
  "msg/HandPoseArray.msg"
  "msg/HeightmapConfig.msg"
  "msg/Histogram.msg"
  "msg/HistogramWithRange.msg"
  "msg/HistogramWithRangeArray.msg"
  "msg/HistogramWithRangeBin.msg"
  "msg/HumanSkeleton.msg"
  "msg/HumanSkeletonArray.msg"
  "msg/ICPResult.msg"
  "msg/ImageDifferenceValue.msg"
  "msg/Int32Stamped.msg"
  "msg/Label.msg"
  "msg/LabelArray.msg"
  "msg/Line.msg"
  "msg/LineArray.msg"
  "msg/ModelCoefficientsArray.msg"
  "msg/Object.msg"
  "msg/ObjectArray.msg"
  "msg/PanoramaInfo.msg"
  "msg/ParallelEdge.msg"
  "msg/ParallelEdgeArray.msg"
  "msg/PeoplePose.msg"
  "msg/PeoplePoseArray.msg"
  "msg/PlotData.msg"
  "msg/PlotDataArray.msg"
  "msg/PointsArray.msg"
  "msg/PolygonArray.msg"
  "msg/PosedCameraInfo.msg"
  "msg/QueryAndProbability.msg"
  "msg/QuestionAndAnswerText.msg"
  "msg/Rect.msg"
  "msg/RectArray.msg"
  "msg/RotatedRect.msg"
  "msg/RotatedRectStamped.msg"
  "msg/Segment.msg"
  "msg/SegmentArray.msg"
  "msg/SegmentStamped.msg"
  "msg/SimpleHandle.msg"
  "msg/SimpleOccupancyGrid.msg"
  "msg/SimpleOccupancyGridArray.msg"
  "msg/SlicedPointCloud.msg"
  "msg/SnapItRequest.msg"
  "msg/SparseImage.msg"
  "msg/SparseOccupancyGrid.msg"
  "msg/SparseOccupancyGridArray.msg"
  "msg/SparseOccupancyGridCell.msg"
  "msg/SparseOccupancyGridColumn.msg"
  "msg/Spectrum.msg"
  "msg/TimeRange.msg"
  "msg/Torus.msg"
  "msg/TorusArray.msg"
  "msg/TrackerStatus.msg"
  "msg/TrackingStatus.msg"
  "msg/VQAResult.msg"
  "msg/VectorArray.msg"
  "msg/WeightedPoseArray.msg"
  "srv/CallPolygon.srv"
  "srv/CallSnapIt.srv"
  "srv/CheckCircle.srv"
  "srv/CheckCollision.srv"
  "srv/EnvironmentLock.srv"
  "srv/EuclideanSegment.srv"
  "srv/ICPAlign.srv"
  "srv/ICPAlignWithBox.srv"
  "srv/NonMaximumSuppression.srv"
  "srv/PolygonOnEnvironment.srv"
  "srv/RobotPickupReleasePoint.srv"
  "srv/SaveMesh.srv"
  "srv/SetDepthCalibrationParameter.srv"
  "srv/SetLabels.srv"
  "srv/SetPointCloud2.srv"
  "srv/SetTemplate.srv"
  "srv/SnapFootstep.srv"
  "srv/SwitchTopic.srv"
  "srv/TowerPickUp.srv"
  "srv/TowerRobotMoveCommand.srv"
  "srv/TransformScreenpoint.srv"
  "srv/UpdateOffset.srv"
  "srv/WhiteBalance.srv"
  "srv/WhiteBalancePoints.srv"
  "action/ClassificationTask.action"
  "action/VQATask.action"
  DEPENDENCIES std_msgs geometry_msgs sensor_msgs pcl_msgs builtin_interfaces action_msgs jsk_footstep_msgs
)

ament_export_dependencies(rosidl_default_runtime)
ament_package()
